Sources/project/core/urls.py
from django.urls        import path

from .                  import views

import uuid

app_name='core'
urlpatterns = [

    #########
    # Admin #
    #########

    path('admin/', views.admin, name='admin'),

    ###############
    # UserManager #
    ###############

    # User

    path('user/', views.user_list,
        name = 'user_list'),
    path('user/job', views.user_list_job,
        name = 'user_list'),
    path('user/new', views.user_new,
        name = 'user_new'),
    path('user/edit/<int:user_id>', views.user_edit,
        name = 'user_edit'),
    path('user/<int:user_id>', views.user_info,
        name = "user_info"),
    path('user/delete/<int:user_id>', views.user_delete,
        name = 'user_delete'),
    path('user/job/new', views.job_new,
        name = 'job_new'),

    #################
    # ObjectManager #
    #################

    path('object/', views.object_list,
         name = "object_list"),
    path('object/stock', views.object_stock_list,
         name = "object_stock_list"),
    path('object/new/', views.object_new,
         name = "object_new"),
    path('object/new/type', views.object_type_new,
         name = "object_type_new"),
    path('object/new/get_type_form', views.get_type_form,
        name = "get_type_form"),
    path('object/<uuid:object_id>', views.object_info,
        name = "object_info"),

    ##################
    # HistoryManager #
    ##################

    path('object/change/<uuid:object_id>', views.object_to_stock,
        name = 'object_to_stock'),
    path('object/stock/change/<uuid:object_id>', views.object_to_user,
        name = 'object_to_user'),
    path('object/state/new', views.object_state_new,
        name = 'object_state_new'),

    ##################
    # CommandManager #
    ##################

    path('command/', views.command_list,
        name = 'command_list'),
    path('command/new', views.command_new,
        name = 'command_new'),
    path('command/<uuid:command_id>', views.command_info,
        name = 'command_info'),

    #################
    # VendorManager #
    #################

    path('vendor/', views.vendor_list,
        name = 'vendor_list'),
    path('vendor/new', views.vendor_new,
        name = 'vendor_new'),
    path('vendor/<int:vendor_id>', views.vendor_info,
        name = 'vendor_info'),

    path('login/', views.login, name='login'),
    path('', views.user_list, name='user_list')
]

Sources/project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    path('favicon.ico', favicon_view),
    path('administration/', admin.site.urls),
    path('', include('core.urls')),
]

Sources/project/templates/form_template.html
{% if prefix_icon %}
	<i class='material-icons prefix'>{{prefix_icon}}</i>
{% endif %}

{# ################################################ #}
{# ############   ###  TEXT  ###   ################ #}
{# ################################################ #}

{% if form_type == 'text' %}

<input type='{{ form_type }}'

       name='{{ form_elem.html_name }}'
       class='validate
			{% if form_elem.errors %}
				invalid
			{% endif %}'

		id='{{ form_elem.id_for_label }}'

		value=
		{% if form_elem.value != None %}
			'{{ form_elem.value }}'
		{% else %}
			''
		{% endif %}

		{% if form_elem.field.max_length %}
			maxlength='{{ form_elem.field.max_length }}'
		{% endif %}
		
		{% if form_elem.field.required %}
			required
		{% endif %}
>

<label for='{{ form_elem.id_for_label }}'>{{ form_elem.label }}</label>
<label	class='helper-text' for='{{ form_elem.id_for_label }}'
		data-error='{% if form_elem.errors%}{% for error in form_elem.errors %}{{error}}{% endfor %}{% else %}Valeur incorrecte{% endif %}'></label>

{# ################################################# #}
{# ############   ###  EMAIL  ###   ################ #}
{# ################################################# #}

{% elif form_type == 'email' %}

<input type='email'

       name='{{ form_elem.html_name }}'
       class='validate 
			{% if form_elem.errors %}
				invalid
			{% endif %}'

		id='{{ form_elem.id_for_label }}'

		value=
		{% if form_elem.value != None %}
			'{{ form_elem.value }}'
		{% else %}
			''
		{% endif %}

		{% if form_elem.field.max_length %}
			maxlength='{{ form_elem.field.max_length }}'
		{% endif %}
		
		{% if form_elem.field.required %}
			required
		{% endif %}
>
<label for='{{ form_elem.id_for_label }}'>{{ form_elem.label }}</label>
<label	class='helper-text' for='{{ form_elem.id_for_label }}'
		data-error='{% if form_elem.errors%}{% for error in form_elem.errors %}{{error}}{% endfor %}{% else %}Valeur incorrecte{% endif %}'></label>

{# ################################################ #}
{# ############   ###  DATE  ###   ################ #}
{# ################################################ #}

{% elif form_type == 'date' %}

<input type='date'

       name='{{ form_elem.html_name }}'
       class='datepicker
       		validate 
			{% if form_elem.errors %}
				invalid
			{% endif %}'

		id='{{ form_elem.id_for_label }}'

		value=
		{% if form_elem.value != None %}
			'{{ form_elem.value }}'
		{% else %}
			''
		{% endif %}

		{% if form_elem.field.max_length %}
			maxlength='{{ form_elem.field.max_length }}'
		{% endif %}
		
		{% if form_elem.field.required %}
			required
		{% endif %}
>

<label for='{{ form_elem.id_for_label }}'>{{ form_elem.label }}</label>
<label class='helper-text' for='{{ form_elem.id_for_label }}' data-error='Valeur incorrecte'></label>


{# ############################################### #}
{# #############   ###  SELECT ###   ############# #}
{# ############################################### #}
{% elif form_type == 'select' %}

<select
		name='{{ form_elem.html_name }}'
		id='{{ form_elem.id_for_label }}'
		{% if form_elem.value != None %}
			value='{{ form_elem.value }}'
		{% endif %}
		{% if form_elem.field.required %}
			required
		{% endif %}	
		class='select_zone'
>

	{% for pk, name in form_elem.field.choices %}
		{% if form_elem.value == pk %}
			<option value={{ pk }} selected>{{ name }}</option>
		{% else %}
			<option value={{ pk }}>{{ name }}</option>
		{% endif %}
	{% endfor %}

</select>

{# ######################################################## #}
{# #############   ###  SELECT MULTIPLE ###   ############# #}
{# ######################################################## #}
{% elif form_type == 'select_multiple' %}

<select multiple
		name='{{ form_elem.html_name }}'
		id='{{ form_elem.id_for_label }}'
		{% if form_elem.value != None %}
			value='{{ form_elem.value }}'
		{% endif %}
		{% if form_elem.field.required %}
			required
		{% endif %}
		class='select_zone'
>

	{% for pk, name in form_elem.field.choices %}
		{% if pk in form_elem.value %}
			<option value={{ pk }} selected>{{ name }}</option>
		{% else %}
			<option value={{ pk }}>{{ name }}</option>
		{% endif %}
	{% endfor %}

</select>

<label for='{{ form_elem.id_for_label }}'>{{ form_elem.label }}</label>
<label	class='helper-text' for='{{ form_elem.id_for_label }}'
		data-error='{% if form_elem.errors%}{% for error in form_elem.errors %}{{error}}{% endfor %}{% else %}Valeur incorrecte{% endif %}'></label>

{# ##################################################### #}
{# #############   ###  SELECT COLOR ###   ############# #}
{# ##################################################### #}
{% elif form_type == 'select_color' %}

<select
		name='{{ form_elem.html_name }}'
		id='{{ form_elem.id_for_label }}'
		{% if form_elem.value != None %}
			value='{{ form_elem.value }}'
		{% endif %}
		{% if form_elem.field.required %}
			required
		{% endif %}	
		class='select_zone'
>

	{% for pk, name in form_elem.field.choices %}
		<option class='indigo-text' value={{ pk }} style='background-color:{{name}};' data-icon='{{name}}'>{{ name }}</option>
	{% endfor %}

</select>

<label for='{{ form_elem.id_for_label }}'>{{ form_elem.label }}</label>
<label	class='helper-text' for='{{ form_elem.id_for_label }}'
		data-error='{% if form_elem.errors%}{% for error in form_elem.errors %}{{error}}{% endfor %}{% else %}Valeur incorrecte{% endif %}'></label>

{# ################################################ #}
{# ############   ###  TEXT AREA ###   ############ #}
{# ################################################ #}
{% elif form_type == 'text_area' %}

<textarea
       name='{{ form_elem.html_name }}'
       class='materialize-textarea
       		validate 
			{% if form_elem.errors %}
				invalid
			{% endif %}'
		id='{{ form_elem.id_for_label }}'
		{% if form_elem.field.required %}
			required
		{% endif %}
>
{% if form_elem.value != None %}'{{ form_elem.value }}'{% endif %}
</textarea>

<label for='{{ form_elem.id_for_label }}'>{{ form_elem.label }}</label>
<label	class='helper-text' for='{{ form_elem.id_for_label }}'
		data-error='{% if form_elem.errors%}{% for error in form_elem.errors %}{{error}}{% endfor %}{% else %}Valeur incorrecte{% endif %}'></label>

{# ################################################ #}
{# #############   ###  NUMBER  ###   ############# #}
{# ############################################### #}
{% elif form_type == 'number' %}


<input type='{{ form_type }}'

       name='{{ form_elem.html_name }}'
       class='validate 
			{% if form_elem.errors %}
				invalid
			{% endif %}'

		id='{{ form_elem.id_for_label }}'

		value=
		{% if form_elem.value != None %}
			'{{ form_elem.value }}'
		{% else %}
			''
		{% endif %}
		
		{% if form_elem.field.required %}
			required
		{% endif %}
>

<label for='{{ form_elem.id_for_label }}'>{{ form_elem.label }}</label>
<label class='helper-text' for='{{ form_elem.id_for_label }}' data-error='Valeur incorrecte'></label>

{% endif %}

Sources/project/templates/leftNavBar.html
{% block sidenavbar %}

<ul id="mobile-version" class="sidenav sidenav-fixed">

	<li class="indigo center white-text">
		Navigation - Administration
	</li>

	<ul class="collapsible">

		<li class="bold">
			<a class="collapsible-header waves-effect">Administration</a>
			<div class="collapsible-body">
				<ul>
					<li><a href="{% url 'core:job_new' %}">Ajouter un nouvel emploi</a></li>
					<li><a href="{% url 'core:object_type_new' %}">Ajouter un nouveau type d'objet</a></li>
					<li><a href="{% url 'core:object_state_new' %}">Ajouter un nouvel etat d'objet</a></li>
					<li><a href="{% url 'core:vendor_new' %}">Ajouter un nouveau fournisseur</a></li>
				</ul>
			</div>
		</li>

		<li class="bold">
			<a class="collapsible-header waves-effect">
				Utilisateurs
			</a>
			<div class="collapsible-body">
				<ul>
					<li><a href="{% url 'core:user_new' %}">Ajouter</a></li>
					<li><a href="{% url 'core:user_list' %}">Liste</a></li>
				</ul>
			</div>
		</li>

		<li class="bold">
			<a class="collapsible-header waves-effect">Matériel</a>
			<div class="collapsible-body">
				<ul>
					<li><a href="{% url 'core:object_new' %}">Ajouter</a></li>
					<li><a href="{% url 'core:object_stock_list' %}">En stock</a></li>
					<li><a href="{% url 'core:object_list' %}">Attribué</a></li>
					<li><a href="#">Rechercher</a></li>
				</ul>
			</div>
		</li>

		<li class="bold">
			<a class="collapsible-header waves-effect">Fournisseurs</a>
			<div class="collapsible-body">
				<ul>
					<li><a href="{% url 'core:command_new' %}">Nouvelle commande</a></li>
					<li><a href="{% url 'core:command_list' %}">Liste des commandes</a></li>
					<li><a href="{% url 'core:vendor_list' %}">Liste des fournisseurs</a></li>
				</ul>
			</div>
		</li>

		<li class="bold">
			<a href="{% url 'core:admin' %}"
				class="waves-effect">Statistiques</a>
		</li>
	</ul>
</ul>

{% endblock sidenavbar %}

Sources/project/templates/main.html
{% load static %}

<!DOCTYPE html>
<html>

	<head>
		<title>
			{% block title %}
				{% if title %}
					{{ title }}
				{% else %}
					GPIP
				{% endif %}
			{% endblock %}
		</title>

		{% block head %}
		{% endblock head %}

		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
		<link rel="stylesheet" href="{% static "css/materialize.css"%}">

		<link rel="stylesheet" href="{% static "css/navbar.css" %}">

	</head>

	<body>

	{% block navbar %}

		{% include "leftNavBar.html" %}
		{% include "topNavBar.html" %}

	{% endblock navbar %}

	<main>
    	<div class="container">
			{% include "navTitle.html" %}
			<br>
			{% block content %}
				No content
				<br>
			{% endblock content %}
		</div>
	</main>

    {% block footer %}
    {% endblock footer %}

    <!-- Scripts -->
    <div id="scripts">
    <!-- JQuery 3.3.1 -->
    <script
      src="{% static 'js/jquery.js' %}"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous">
    </script>
    <!-- Materialize 1.0.0 -->
    <script src="{% static 'js/materialize.js' %}">
    </script>

    <!-- Script Navbar mobile version -->
    <script>
      $(document).ready(function()
      	{
	     	$('.sidenav').sidenav();
      	}
      );
    </script>
    <!-- Collapsible (dropdown for left sidebar) -->
    <script>
      $(document).ready(function()
      	{
    		$('.collapsible').collapsible();
      	}
      );
    </script>
    <script>
		M.AutoInit();
    </script>
    {% block script %}
    {% endblock script %}
    </div>
  </body>
</html>

Sources/project/templates/navTitle.html
{% if navLinks %}
<ul id="navTitle" class="dropdown-content">
	{% for link in navLinks %}
	<li>
		<a href='{{ link.ref }}'>
		{{ link.name }}
		</a>
	</li>
	{% endfor %}
</ul>
{% endif %}

{% if navTitle %}
<br>
<br>
<nav>
	<div class="nav-wrapper indigo">
		<i class="material-icons left">chevron_right</i>
		<a href="#" class="brand-logo">{{ navTitle }}</a>

		{% if navLinks %}
		<ul class="right">
			<!-- Dropdown Trigger -->
			<li>
				<a class="dropdown-trigger" href="#!" data-target="navTitle">
					{% if navLinkActive %}
						{{ navLinkActive }}
					{% else %}
						Plus/Options
					{% endif %}
					<i class="material-icons right">arrow_drop_down</i>
				</a>
			</li>
		</ul>
		{% endif %}
	</div>
<br>
</nav>
{% endif %}

Sources/project/templates/redirect.html
{% extends "main.html" %}

{% block title %}
{{ title }}
{% endblock title %}

{% block content %}

<div class="container">

  <h1>{{ htitle }}</h1>

  <a href="{{ link }}"><h4>Redirection</h4></a>

  <div class="progress indigo">
    <div class="indeterminate"></div>
  </div>
</div>

{% endblock content %}

{% block script %}

<!-- Redirection script -->
<script>
  function redirection()
  {
    document.location.href="{{ link }}";
  }

  window.setTimeout(redirection, 3500);
</script>

{% endblock script %}

Sources/project/templates/topNavBar.html
{% block topnavbar %}
<div class="topnavbar_container">
	<div class="navbar navbar-fixed">
		<nav>
			<div class="nav-wrapper indigo center-align">
				<a href="#" id="main_title" class="center brand-logo">GPIP<i class='material-icons'>card_travel</i></a>
				<a href="#" data-target="mobile-version" class="sidenav-trigger">
					<i class="material-icons">menu</i>
				</a>
			</div>
		</nav>
	</div>
</div>
{% endblock topnavbar %}