Sources/project/core/urls.py
from django.urls        import path

from .                  import views

import uuid

app_name='core'
urlpatterns = [

    #########
    # Admin #
    #########

    path('admin/', views.admin, name='admin'),

    ###############
    # UserManager #
    ###############

    # User

    path('user/', views.user_list,
        name = 'user_list'),
    path('user/job', views.user_list_job,
        name = 'user_list'),
    path('user/new', views.user_new,
        name = 'user_new'),
    path('user/edit/<int:user_id>', views.user_edit,
        name = 'user_edit'),
    path('user/<int:user_id>', views.user_info,
        name = "user_info"),
    path('user/delete/<int:user_id>', views.user_delete,
        name = 'user_delete'),
    path('user/job/new', views.job_new,
        name = 'job_new'),

    #################
    # ObjectManager #
    #################

    path('object/', views.object_list,
         name = "object_list"),
    path('object/stock', views.object_stock_list,
         name = "object_stock_list"),
    path('object/new/', views.object_new,
         name = "object_new"),
    path('object/new/type', views.object_type_new,
         name = "object_type_new"),
    path('object/new/get_type_form', views.get_type_form,
        name = "get_type_form"),
    path('object/<uuid:object_id>', views.object_info,
        name = "object_info"),

    ##################
    # HistoryManager #
    ##################

    path('object/change/<uuid:object_id>', views.object_to_stock,
        name = 'object_to_stock'),
    path('object/stock/change/<uuid:object_id>', views.object_to_user,
        name = 'object_to_user'),
    path('object/state/new', views.object_state_new,
        name = 'object_state_new'),

    ##################
    # CommandManager #
    ##################

    path('command/', views.command_list,
        name = 'command_list'),
    path('command/new', views.command_new,
        name = 'command_new'),
    path('command/<uuid:command_id>', views.command_info,
        name = 'command_info'),

    #################
    # VendorManager #
    #################

    path('vendor/', views.vendor_list,
        name = 'vendor_list'),
    path('vendor/new', views.vendor_new,
        name = 'vendor_new'),
    path('vendor/<int:vendor_id>', views.vendor_info,
        name = 'vendor_info'),

    path('login/', views.login, name='login'),
    path('', views.user_list, name='user_list')
]

Sources/project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    path('favicon.ico', favicon_view),
    path('administration/', admin.site.urls),
    path('', include('core.urls')),
]

Sources/project/core/_views/forms.py
from django.shortcuts   import render
from django.http        import HttpResponse
from django.shortcuts   import redirect

from ..models            import User, UserRole, UserJob
from ..models            import Object, ObjectType, ObjectDataType, ObjectData
from ..models            import ObjectHistory, ObjectState
from ..models            import Command, CommandState
from ..models            import Vendor


from ..forms             import UserForm, RoleForm, JobForm
from ..forms             import ObjectForm, ObjectTypeForm, ObjectDataTypeForm
from ..forms             import ObjectDataFormSet, ObjectDataTypeFormSet
from ..forms             import ObjectToStockForm, ObjectToUserForm, ObjectStateForm
from ..forms             import VendorForm, CommandForm
from ..forms             import LoginForm

from ..forms             import Command__object_form, Command__object_data_form
from ..forms             import command_object_formset, command_object_data_formset


from ..utils import render_to_pdf

from django.core.serializers import serialize
import datetime
from array              import array

from ._forms.history    import object_to_stock, object_to_user, object_state_new

from ._forms.user       import user_new, user_edit, user_delete
from ._forms.user       import job_new, job_edit
from ._forms.user       import role_new, role_edit

from ._forms.command    import command_new

from ._forms.vendor     import vendor_new

from ._forms.object     import object_new, object_type_new

from ._forms.auth      import login

Sources/project/core/forms.py
from django             import forms
from django.forms       import ModelForm, formset_factory

from .models                    import User, UserRole, UserJob
from .models                    import Object, ObjectData
from .models                    import ObjectType, ObjectDataType
from .models                    import ObjectHistory, ObjectState

from .models                    import Vendor, Command, CommandState

####################

##########
# Object #
##########

####################

class           ObjectDataForm(forms.ModelForm):

    hidden = forms.IntegerField()

    class       Meta:
        model   = ObjectData
        fields  = ['value']
        labels = {
            'value': 'Valeur',
        }

ObjectDataFormSet = formset_factory(ObjectDataForm, extra = 0)

class           ObjectTypeForm(forms.ModelForm):
    name = forms.CharField(min_length = 4, max_length = 255)
    
    class       Meta:
        model = ObjectType
        fields = ['name']
        labels = {
            'name': 'Nom',
        }


class           ObjectDataTypeForm(forms.ModelForm):
    class       Meta:
        model = ObjectDataType
        fields = ['name', 's_type', 'mendatory', 'visible']
        exclude = ['objectType']
        labels = {
            'name': 'Nom',
            's_type': 'Type de donnée',
            'mendatory': 'Obligatoire',
            'visible': 'Visible'
        }


ObjectDataTypeFormSet = formset_factory(ObjectDataTypeForm, extra = 0)

class           ObjectForm(forms.ModelForm):
    class Meta:
        model = Object
        fields = ['name', 'user', 'objectType']
        exclude = ['depth', 'objectIn', 'command', 'user']
        labels = {
            'name': 'Nom',
            'user': 'Utilisateur',
            'objectType': 'Type d\'object'
        }

####################

###########
# History #
###########

####################

class           ObjectToStockForm(forms.ModelForm):
    class Meta:
        model = ObjectHistory
        fields = ['date', 'comment', 'position', 'objectState']
        exclude = ['user', 'objectShown']
        labels = {
            'date': 'Date de remise',
            'comment': 'Commentaire',
            'position': 'Lieu de remise',
            'objectState': 'Etat de l\'object'
        }

class           ObjectToUserForm(forms.ModelForm):
    class Meta:
        model = ObjectHistory
        fields = ['date', 'position', 'objectState', 'user']
        exclude = ['objectShown', 'comment']
        labels = {
            'date': 'Date de remise',
            'position': 'Lieu de remise',
            'objectState': 'Etat de l\'object',
            'user': 'Utilisateur'
        }

class           ObjectStateForm(forms.ModelForm):
#    CHOICES = (
#        ('1', '#1b5e20'),
#        ('2', '#388e3c'),
#       ('3', '#4caf50'),
#        ('4', '#8bc34a'),
#        ('5', '#cddc39'),
#        ('6', '#ffeb3b'),
#        ('7', '#fbc02d'),
#        ('8', '#f57f17'),
#        ('9', '#ff5722'),
#        ('10', '#f44336')
#    )
#    color = forms.ChoiceField(choices=CHOICES)

    class Meta:
        model = ObjectState
        fields = ['name', 'color']
        labels = {
            'name': 'Nom',
            'color': 'Couleur'
        }

####################

########
# User #
########

####################

class RoleForm(forms.ModelForm):
    class Meta:
        model = UserRole
        fields = ['name']
        labels = {
            'name': 'Nom'
        }
        
class JobForm(forms.ModelForm):
    class Meta:
         model = UserRole
         fields = ['name']
         labels = {
            'name': 'Nom'
         }

class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['forname', 'name', 'email', 'oAuthKey', 'entryDate', 'outDate', 'userRole', 'userJob']
        labels = {
            'forname': 'Prénom',
            'name': 'Nom',
            'email': 'Email',
            'oAuthKey': 'Clef d\'identification',
            'entryDate': 'Date d\'arrivé',
            'outDate': 'Date de départ',
            'userRole': 'Rôle',
            'userJob': 'Poste'   
        }

class VendorForm(forms.ModelForm):
    class Meta:
         model = Vendor
         fields = ['name', 'adress', 'email', 'comment']
         labels = {
            'name': 'Nom',
            'adress': 'Adresse de l\'entreprise',
            'email': 'Email du contact',
            'comment': 'Informations additionnelles'
         }

class CommandForm(forms.ModelForm):

    class Meta:
        model = Command
        fields = '__all__'
        exclude = ['commandState']

class   Command__object_form(forms.ModelForm):

    count = forms.IntegerField(min_value = 1, required = 1)

    class Meta:
        model = Object
        fields = ['name', 'objectType', 'count']

command_object_formset = formset_factory(Command__object_form, extra = 0)

class   Command__object_data_form(forms.ModelForm):
    class Meta:
        model = ObjectData
        fields = ['value', 'objectDataType']

command_object_data_formset = formset_factory(Command__object_data_form, extra = 0)

# Login
class   LoginForm(forms.Form):
    login = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

Sources/project/core/views.py
from django.shortcuts   import render
from django.http        import HttpResponse
from django.shortcuts   import redirect

#from django.core.serializers import serialize
#from django.http        import JsonResponse
#from datetime           import date
#from array              import array

# List views
from ._views.list       import user_list
from ._views.list       import user_list_job
from ._views.list       import object_list
from ._views.list       import object_stock_list
from ._views.list       import command_list
from ._views.list       import vendor_list

# Form views
from ._views.forms      import user_new
from ._views.forms      import job_new
from ._views.forms      import role_new
from ._views.forms      import object_new
from ._views.forms      import object_type_new
from ._views.forms      import object_to_stock
from ._views.forms      import object_to_user
from ._views.forms      import object_state_new
from ._views.forms      import command_new
from ._views.forms      import vendor_new

from ._views.forms      import user_edit
from ._views.forms      import job_edit
from ._views.forms      import role_edit

from ._views.forms      import user_delete

from ._views.forms      import login

# Info views
from ._views.infos      import user_info
from ._views.infos      import object_info
from ._views.infos      import vendor_info
from ._views.infos      import command_info
from ._views.infos      import admin

# Ajax section
from ._views.ajax       import get_type_form

from .models import User, UserRole, UserJob


# TODO: Clean this check (I'm learning django)

# Check for the basic data
if (not (UserRole.objects.filter(name = '__STOCK__').exists())):
    UserRole.objects.create(name = '__STOCK__')

if (not (UserJob.objects.filter(name = '__STOCK__').exists())):
    UserJob.objects.create(name = '__STOCK__')

if (not (User.objects.filter(name = '__STOCK__', forname = '__STOCK__').exists())):
    User.objects.create(
        name = '__STOCK__',
        forname = '__STOCK__',
        oAuthKey = 'None',
        userRole = UserRole.objects.get(name = '__STOCK__'),
        userJob = UserJob.objects.get(name = '__STOCK__'),
    )

if (not (User.objects.filter(name = '__PENDING__', forname = '__PENDING__').exists())):
    User.objects.create(
        name = '__PENDING__',
        forname = '__PENDING__',
        oAuthKey = 'None',
        userRole = UserRole.objects.get(name = '__STOCK__'),
        userJob = UserJob.objects.get(name = '__STOCK__'),
    )

from .models import Object
def test(request):
    get = Object.objects.get(pk = 'cbe29927-c694-4bec-b776-810bc00af604').last_object_state()
    return HttpResponse('Le dernier état de l\'object est: ' + get.objectState.name)

def index(request):
    return HttpResponse("Index: objectManager")

Sources/project/core/templates/list/object.html
{% extends "main.html" %}
{% load static %}

{% block content %}

{% if objectList %}

{% regroup objectList by objectType.name as objects_by_type %}

{% for objects in objects_by_type %}

<h5>{{ objects.grouper }}<h5>

<table style='border: 2px solid #3f51b5' class="striped centered responsive-table">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Proprietaire</th>
      <th>Etat</th>
      <th>Informations</th>
    </tr>
  </thead>
  <tbody>
    {% for object in objects.list %}
    <tr>
		<td> {{ object.name }} </td>
    	<td> {{ object.user.forname }} {{ object.user.name }} </td>
    	<td>
			{{ object.state.objectState.name }}
      		<i class='material-icons' style='color: {{ object.state.objectState.color }}'>
    	  		fiber_manual_record
   		   	</i>
		</td>
    	<td>
    		<a class='btn indigo' href='{% url 'core:object_info' object.pk %}'>info</a>
    	</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<br>

{% endfor %}

{% else %}

<h1> Aucun contenu disponible </h1>

{% endif %}
{% endblock content %}

Sources/project/core/templates/list/object__stock.html
{% extends "main.html" %}
{% load static %}

{% block content %}

{% if objectList %}

{% regroup objectList by objectType.name as objects_by_type %}

{% for objects in objects_by_type %}

<br>
<h5 class='subtitle'> {{ objects.grouper }}<h5>

<table style='border: 2px solid #3f51b5;' class="striped centered responsive-table">
  <thead>
    <tr class='center-align' >
      <th>Nom</th>
      <th>Attribution</th>
      <th>Détail</th>
      <th>Etat</th>
    </tr>
  </thead>
  <tbody>
    {% for object in objects.list %}
    <tr>
      <td style='width: 300px'> {{ object.name }} </td>
      <td>
		<a class='btn waves-effect waves-light indigo' href='{% url 'core:object_to_user' object.ref %}'>
			<i class='material-icons'>
				send
			</i>
		</a>
      </td>
      <td>
      		<a class='btn white black-text' href='{% url 'core:object_info' object.pk %}'>
				<i class='material-icons'>
					list
				</i>      			
      		</a>
      </td>
      <td>
		{{ object.state.objectState.name }}
		<i class='material-icons' style='color: {{ object.state.objectState.color }}'>
			fiber_manual_record
		</i>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<br>

{% endfor %}

{% else %}

<h4> Aucun matériel en stock actuellement </h4>

{% endif %}
{% endblock content %}

Sources/project/core/templates/list/user.html
{% extends "main.html" %}
{% load static %}

{% block title %}Utilisateurs{% endblock title %}

{% block content %}

<!-- list all -->
{% if userList %}

<table class="striped centered responsive-table">

  <thead>
    <tr>
      <th>Nom</th>
      <th>Prénom</th>
      <th>Email</th>
      <th>Date de sortie</th>
      <th>Job</th>
      <th>Informations</th>
    </tr>
  </thead>

  <tbody>
    {% for user in userList %}

		{% if user.entryDate %}
			{% if user.entryDate > today %}
				<tr class="green white-text">
			{% elif user.outDate %}
				{% if user.outDate < today %}
					<tr class="red white-text">
				{% else %}
					<tr class="orange white-text">
				{% endif %}
			{% else %}
				<tr>	
			{% endif %}
		{% elif user.outDate %}
			{% if user.outDate < today %}
					     <tr class="red white-text">
			{% else %}
					     <tr class="orange white-text">
			{% endif %}
		{% else %}
			<tr>
		{% endif %}
		<td>{{ user.name }}</td>
		<td>{{ user.forname }}</td>
		<td>{{ user.email | default:"x" }}</td>
		<td>{{ user.outDate | default:"x" }}</td>
		<td>{{ user.userJob.name }}</td>
		<td>
			<a class="waves-effect waves-light btn indigo" href="/user/{{user.pk}}">
				Lien<i class="material-icons right">send</i>
			</a>
		</td>
		</tr>
	{% endfor %}
  </tbody>
  <br>
</table>
{% else %}

  Aucun utilisateur n'est enregistré pour le moment<br>

{% endif %}

{% endblock content %}

Sources/project/core/templates/list/user__by_job.html
{% extends "main.html" %}
{% load static %}

{% block title %}Utilisateurs{% endblock title %}

{% block content %}

<!-- list by job -->
{% if userListJob %}

{% regroup userListJob by userJob.name as user_job_list %}

{% for users_by_job in user_job_list %}

<h5>{{ users_by_job.grouper }}</h5>

<table class="striped centered responsive-table">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Prénom</th>
      <th>Email</th>
      <th>Date de sortie</th>
      <th>Informations</th>
    </tr>
  </thead>
  <tbody>
    {% for user in users_by_job.list %}

	{% if user.entryDate %}
		{% if user.entryDate > today %}
			<tr class="green white-text">
		{% elif user.outDate %}
			{% if user.outDate < today %}
				<tr class="red white-text">
			{% else %}
				<tr class="orange white-text">
			{% endif %}
		{% else %}
			<tr>	
		{% endif %}
	{% elif user.outDate %}
		{% if user.outDate < today %}
				     <tr class="red white-text">
		{% else %}
				     <tr class="orange white-text">
		{% endif %}
	{% else %}
		<tr>
	{% endif %}

      <td>{{ user.name }}</td>
      <td>{{ user.forname }}</td>
      <td>{{ user.email | default:"x" }}</td>
	<td>{{ user.outDate | default:"x" }}</td>
	<td>
	  <a class="waves-effect waves-light btn indigo" href="/user/{{user.pk}}">
	    Lien<i class="material-icons right">send</i>
	  </a>
	</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<br>
    {% endfor %}

{% else %}

Aucun utilisateur n'est enregistré pour le moment

{% endif %}

{% endblock content %}

Sources/project/core/templates/list/vendor.html
{% extends "main.html" %}
{% load static %}

{% block content %}

{% if vendor_list %}

<table class="striped centered responsive-table">

  <thead>
    <tr>
      <th>Nom</th>
      <th>Adresse</th>
      <th>Contact</th>
      <th>Informations</th>
    </tr>
  </thead>

  <tbody>
	{% for vendor in vendor_list %}
	<tr>
		<td>{{ vendor.name }}</td>
		<td>{{ vendor.adress }}</td>
		<td>{{ vendor.email | default:"x" }}</td>
		<td>
			<a class="waves-effect waves-light btn indigo" href="{% url 'core:vendor_info' vendor.pk %}">
				Lien<i class="material-icons right">send</i>
			</a>
		</td>
		</tr>
	{% endfor %}
  </tbody>
  <br>
</table>
{% else %}

  Aucun fournisseur n'est enregistré pour le moment<br>

{% endif %}

{% endblock content %}