Sources/project/core/urls.py
from django.urls        import path

from .                  import views

import uuid

app_name='core'
urlpatterns = [

    #########
    # Admin #
    #########

    path('admin/', views.admin, name='admin'),

    ###############
    # UserManager #
    ###############

    # User

    path('user/', views.user_list,
        name = 'user_list'),
    path('user/job', views.user_list_job,
        name = 'user_list'),
    path('user/new', views.user_new,
        name = 'user_new'),
    path('user/edit/<int:user_id>', views.user_edit,
        name = 'user_edit'),
    path('user/<int:user_id>', views.user_info,
        name = "user_info"),
    path('user/delete/<int:user_id>', views.user_delete,
        name = 'user_delete'),
    path('user/job/new', views.job_new,
        name = 'job_new'),

    #################
    # ObjectManager #
    #################

    path('object/', views.object_list,
         name = "object_list"),
    path('object/stock', views.object_stock_list,
         name = "object_stock_list"),
    path('object/new/', views.object_new,
         name = "object_new"),
    path('object/new/type', views.object_type_new,
         name = "object_type_new"),
    path('object/new/get_type_form', views.get_type_form,
        name = "get_type_form"),
    path('object/<uuid:object_id>', views.object_info,
        name = "object_info"),

    ##################
    # HistoryManager #
    ##################

    path('object/change/<uuid:object_id>', views.object_to_stock,
        name = 'object_to_stock'),
    path('object/stock/change/<uuid:object_id>', views.object_to_user,
        name = 'object_to_user'),
    path('object/state/new', views.object_state_new,
        name = 'object_state_new'),

    ##################
    # CommandManager #
    ##################

    path('command/', views.command_list,
        name = 'command_list'),
    path('command/new', views.command_new,
        name = 'command_new'),
    path('command/<uuid:command_id>', views.command_info,
        name = 'command_info'),

    #################
    # VendorManager #
    #################

    path('vendor/', views.vendor_list,
        name = 'vendor_list'),
    path('vendor/new', views.vendor_new,
        name = 'vendor_new'),
    path('vendor/<int:vendor_id>', views.vendor_info,
        name = 'vendor_info'),

    path('login/', views.login, name='login'),
    path('', views.user_list, name='user_list')
]

Sources/project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    path('favicon.ico', favicon_view),
    path('administration/', admin.site.urls),
    path('', include('core.urls')),
]

Sources/project/core/_views/forms.py
from django.shortcuts   import render
from django.http        import HttpResponse
from django.shortcuts   import redirect

from ..models            import User, UserRole, UserJob
from ..models            import Object, ObjectType, ObjectDataType, ObjectData
from ..models            import ObjectHistory, ObjectState
from ..models            import Command, CommandState
from ..models            import Vendor


from ..forms             import UserForm, RoleForm, JobForm
from ..forms             import ObjectForm, ObjectTypeForm, ObjectDataTypeForm
from ..forms             import ObjectDataFormSet, ObjectDataTypeFormSet
from ..forms             import ObjectToStockForm, ObjectToUserForm, ObjectStateForm
from ..forms             import VendorForm, CommandForm
from ..forms             import LoginForm

from ..forms             import Command__object_form, Command__object_data_form
from ..forms             import command_object_formset, command_object_data_formset


from ..utils import render_to_pdf

from django.core.serializers import serialize
import datetime
from array              import array

from ._forms.history    import object_to_stock, object_to_user, object_state_new

from ._forms.user       import user_new, user_edit, user_delete
from ._forms.user       import job_new, job_edit
from ._forms.user       import role_new, role_edit

from ._forms.command    import command_new

from ._forms.vendor     import vendor_new

from ._forms.object     import object_new, object_type_new

from ._forms.auth      import login

Sources/project/core/forms.py
from django             import forms
from django.forms       import ModelForm, formset_factory

from .models                    import User, UserRole, UserJob
from .models                    import Object, ObjectData
from .models                    import ObjectType, ObjectDataType
from .models                    import ObjectHistory, ObjectState

from .models                    import Vendor, Command, CommandState

####################

##########
# Object #
##########

####################

class           ObjectDataForm(forms.ModelForm):

    hidden = forms.IntegerField()

    class       Meta:
        model   = ObjectData
        fields  = ['value']
        labels = {
            'value': 'Valeur',
        }

ObjectDataFormSet = formset_factory(ObjectDataForm, extra = 0)

class           ObjectTypeForm(forms.ModelForm):
    name = forms.CharField(min_length = 4, max_length = 255)
    
    class       Meta:
        model = ObjectType
        fields = ['name']
        labels = {
            'name': 'Nom',
        }


class           ObjectDataTypeForm(forms.ModelForm):
    class       Meta:
        model = ObjectDataType
        fields = ['name', 's_type', 'mendatory', 'visible']
        exclude = ['objectType']
        labels = {
            'name': 'Nom',
            's_type': 'Type de donnée',
            'mendatory': 'Obligatoire',
            'visible': 'Visible'
        }


ObjectDataTypeFormSet = formset_factory(ObjectDataTypeForm, extra = 0)

class           ObjectForm(forms.ModelForm):
    class Meta:
        model = Object
        fields = ['name', 'user', 'objectType']
        exclude = ['depth', 'objectIn', 'command', 'user']
        labels = {
            'name': 'Nom',
            'user': 'Utilisateur',
            'objectType': 'Type d\'object'
        }

####################

###########
# History #
###########

####################

class           ObjectToStockForm(forms.ModelForm):
    class Meta:
        model = ObjectHistory
        fields = ['date', 'comment', 'position', 'objectState']
        exclude = ['user', 'objectShown']
        labels = {
            'date': 'Date de remise',
            'comment': 'Commentaire',
            'position': 'Lieu de remise',
            'objectState': 'Etat de l\'object'
        }

class           ObjectToUserForm(forms.ModelForm):
    class Meta:
        model = ObjectHistory
        fields = ['date', 'position', 'objectState', 'user']
        exclude = ['objectShown', 'comment']
        labels = {
            'date': 'Date de remise',
            'position': 'Lieu de remise',
            'objectState': 'Etat de l\'object',
            'user': 'Utilisateur'
        }

class           ObjectStateForm(forms.ModelForm):
#    CHOICES = (
#        ('1', '#1b5e20'),
#        ('2', '#388e3c'),
#       ('3', '#4caf50'),
#        ('4', '#8bc34a'),
#        ('5', '#cddc39'),
#        ('6', '#ffeb3b'),
#        ('7', '#fbc02d'),
#        ('8', '#f57f17'),
#        ('9', '#ff5722'),
#        ('10', '#f44336')
#    )
#    color = forms.ChoiceField(choices=CHOICES)

    class Meta:
        model = ObjectState
        fields = ['name', 'color']
        labels = {
            'name': 'Nom',
            'color': 'Couleur'
        }

####################

########
# User #
########

####################

class RoleForm(forms.ModelForm):
    class Meta:
        model = UserRole
        fields = ['name']
        labels = {
            'name': 'Nom'
        }
        
class JobForm(forms.ModelForm):
    class Meta:
         model = UserRole
         fields = ['name']
         labels = {
            'name': 'Nom'
         }

class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['forname', 'name', 'email', 'oAuthKey', 'entryDate', 'outDate', 'userRole', 'userJob']
        labels = {
            'forname': 'Prénom',
            'name': 'Nom',
            'email': 'Email',
            'oAuthKey': 'Clef d\'identification',
            'entryDate': 'Date d\'arrivé',
            'outDate': 'Date de départ',
            'userRole': 'Rôle',
            'userJob': 'Poste'   
        }

class VendorForm(forms.ModelForm):
    class Meta:
         model = Vendor
         fields = ['name', 'adress', 'email', 'comment']
         labels = {
            'name': 'Nom',
            'adress': 'Adresse de l\'entreprise',
            'email': 'Email du contact',
            'comment': 'Informations additionnelles'
         }

class CommandForm(forms.ModelForm):

    class Meta:
        model = Command
        fields = '__all__'
        exclude = ['commandState']

class   Command__object_form(forms.ModelForm):

    count = forms.IntegerField(min_value = 1, required = 1)

    class Meta:
        model = Object
        fields = ['name', 'objectType', 'count']

command_object_formset = formset_factory(Command__object_form, extra = 0)

class   Command__object_data_form(forms.ModelForm):
    class Meta:
        model = ObjectData
        fields = ['value', 'objectDataType']

command_object_data_formset = formset_factory(Command__object_data_form, extra = 0)

# Login
class   LoginForm(forms.Form):
    login = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

Sources/project/core/views.py
from django.shortcuts   import render
from django.http        import HttpResponse
from django.shortcuts   import redirect

#from django.core.serializers import serialize
#from django.http        import JsonResponse
#from datetime           import date
#from array              import array

# List views
from ._views.list       import user_list
from ._views.list       import user_list_job
from ._views.list       import object_list
from ._views.list       import object_stock_list
from ._views.list       import command_list
from ._views.list       import vendor_list

# Form views
from ._views.forms      import user_new
from ._views.forms      import job_new
from ._views.forms      import role_new
from ._views.forms      import object_new
from ._views.forms      import object_type_new
from ._views.forms      import object_to_stock
from ._views.forms      import object_to_user
from ._views.forms      import object_state_new
from ._views.forms      import command_new
from ._views.forms      import vendor_new

from ._views.forms      import user_edit
from ._views.forms      import job_edit
from ._views.forms      import role_edit

from ._views.forms      import user_delete

from ._views.forms      import login

# Info views
from ._views.infos      import user_info
from ._views.infos      import object_info
from ._views.infos      import vendor_info
from ._views.infos      import command_info
from ._views.infos      import admin

# Ajax section
from ._views.ajax       import get_type_form

from .models import User, UserRole, UserJob


# TODO: Clean this check (I'm learning django)

# Check for the basic data
if (not (UserRole.objects.filter(name = '__STOCK__').exists())):
    UserRole.objects.create(name = '__STOCK__')

if (not (UserJob.objects.filter(name = '__STOCK__').exists())):
    UserJob.objects.create(name = '__STOCK__')

if (not (User.objects.filter(name = '__STOCK__', forname = '__STOCK__').exists())):
    User.objects.create(
        name = '__STOCK__',
        forname = '__STOCK__',
        oAuthKey = 'None',
        userRole = UserRole.objects.get(name = '__STOCK__'),
        userJob = UserJob.objects.get(name = '__STOCK__'),
    )

if (not (User.objects.filter(name = '__PENDING__', forname = '__PENDING__').exists())):
    User.objects.create(
        name = '__PENDING__',
        forname = '__PENDING__',
        oAuthKey = 'None',
        userRole = UserRole.objects.get(name = '__STOCK__'),
        userJob = UserJob.objects.get(name = '__STOCK__'),
    )

from .models import Object
def test(request):
    get = Object.objects.get(pk = 'cbe29927-c694-4bec-b776-810bc00af604').last_object_state()
    return HttpResponse('Le dernier état de l\'object est: ' + get.objectState.name)

def index(request):
    return HttpResponse("Index: objectManager")

Sources/project/core/templates/forms/command_new.html
{% extends 'main.html' %}
{% load static %}

{% block content %}

	<div id='main__prefix__' class='command row'>
		<div class='command_final'>
					{% include './formset_template/command__object_final.html' %}
		</div>
	
		<div class='command_object'>
			{% include './formset_template/command__object.html' %}
		</div>
		<div class='command_object_data'>
			{% include './formset_template/command__object_data.html' %}
		</div>
	</div>


<form id='command_new' action='{% url 'core:command_new' %}' method='post'>

	{% csrf_token %}

	<div class='card white z-depth-2'>
		<div class='card-content'>

			<div class='row'>
				<div class='input-field col s12 m6'>
					{% with form_elem=form.vendor form_type='select' prefix_icon='' %}
						{% include 'form_template.html' %}
					{% endwith %}
				</div>
				<div class='input-field col s12 m6'>
					{% with form_elem=form.reference form_type='text' prefix_icon='' %}
						{% include 'form_template.html' %}
					{% endwith %}
				</div>
			</div>

		</div>
	</div>

	<div class='manage-object'>
		{{ formset_object.management_form }}		
	</div>

	<div class='manage-command_object_data'>
		{{ formset_object_data.management_form }}		
	</div>

	{% for form_object_data in formset_object_data %}
		/!\ This should not be displayed /!\ [/forms/command_new.html]
	{% endfor %}

	<div id='new_object_data'>

	</div>

	<div class='row'>
		<button class='btn btn-submit waves-effect waves-light indigo disabled right'>
			Terminé
			<i class='material-icons right'>send</i>
		</button>
	</div>
</form>

<div class='card white z-depth-2'>
	<div class='card-content'>
		<h5 class='indigo-text'>Ajouter:</h5>
		<div class='card-action'></div>
		<div class='row centered'>
			<div class='col s12 m6'>
			<button class='btn waves-effect waves-light indigo left' id='new_object'>
				Un matériel nouveau
				<i class='material-icons right'>add_circle</i>
			</button>
			</div>
			<div class='col s12 m6'>

			<button class='btn waves-effect waves-light indigo right' id='existing_object'>
				Se baser sur un matériel
				<i class='material-icons right'>arrow_drop_down_circle</i>
			</button>
			</div>
		</div>
	</div>
</div>

<div id='based_on' class='container' style='display: none;'>
	<div class='card white z-depth-2'>
		<div class='card-content'>
			<h5 class='indigo-text'>Options:</h5>
			<div class='card-action'></div>
			Se base sur:
			
		</div>
	</div>
</div>

<div id='is' class='container' style='display: none;'>
	<div class='card white z-depth-2'>
		<div class='card-content'>
			<h5 class='indigo-text'>Options:</h5>
			<div class='card-action'></div>
			<div class='row'>
				Est un:
				<select id='new_object_select'>
					{% for object_type in select_object_type %}
						<option value={{ object_type.pk }}>{{ object_type.name }}</option>
					{% endfor %}
				</select>
				<br>
				<div class='card-action'></div>
				<a id='new_object_validate' class='btn indigo right'>Valider</a>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

{% block script %}

<!-- Dynamic form -->
<script src='{% static 'js/formset.js'%}'>
</script>

<script src='{% static 'js/command_dynamic.js' %}'>	
</script>

<!-- Auto enable validation button -->
<script src='{% static 'js/form_button.js' %}'>
</script>

<script>
	set_form_checker('#command_new');
</script>

{% endblock script %}

Sources/project/core/templates/forms/history_to_stock.html
{% extends "main.html" %}
{% load static %}

{% block content %}

<form id='history_to_stock' action="{% url 'core:object_to_stock' default_values.object.pk %}" method="post">
	{% csrf_token %}

	<div class='card white z-depth-2'>
		<div class='card-content'>
			<div class='row'>
				<div class='col s12 m6 input-field'>
					<div class='select-wrapper'>
						<select name='{{ default_values.user.name }}'
								id='id_{{ default_values.user.name }}' 
								disabled
						>
								<option value={{ default_values.user.pk }} selected> {{ default_values.user }}</option>
						</select>
						<label for='id_{{ default_values.user.name }}'>
							Utilisateur
						</label>
					</div>				
				</div>
				<div class='col s12 m6 input-field'>
					<div class='select-wrapper'>
						<select name='{{ form.objectShown.name }}'
								id='{{ form.objectShown.id_for_label }}' 
								disabled
						>
								<option value={{ default_values.object.pk }} selected> {{ default_values.object }}</option>
						</select>
						<label for='{{ form.objectShown.id_for_label }}'>
							{{ form.objectShown.label }}
						</label>
					</div>				
				</div>
			</div>
			<div class='row'>
				<div class='input-field col s12 m6'>
					{% with form_elem=form.date form_type='date' prefix_icon='date_range' %}
						{% include 'form_template.html' %}
					{% endwith %}
				</div>
				<div class='input-field col s12 m6 select-wrapper'>
					{% with form_elem=form.objectState form_type='select' %}
						{% include 'form_template.html'%}
					{% endwith %}
				</div>
			</div>
			<div class='row input-field'>
				{% with form_elem=form.position form_type='text' prefix_icon='location_on' %}
					{% include 'form_template.html' %}
				{% endwith %}
			</div>
			<div class='row input-field'>
				{% with form_elem=form.comment form_type='text_area' prefix_icon='' %}
					{% include 'form_template.html' %}
				{% endwith %}
			</div>			
		</div>
	</div>
	<button id='btn-send' class='btn btn-submit waves-effect waves-light indigo disabled right'>
	   	Ajouter
	   	<i class="material-icons right">send</i>
	</button>
</form>

{% endblock content %}

{% block script %}

<!-- Selection list form -->
<script src="{% static "js/load/load_select.js" %}">
</script>

<!-- Datepicker form -->
<script src="{% static "js/load/load_datepicker_fr.js" %}">
</script>

<script src='{% static 'js/form_button.js' %}'>
</script>

<script>
	set_form_checker('#history_to_stock');
</script>

{% endblock script %}

Sources/project/core/templates/forms/history_to_user.html
{% extends "main.html" %}
{% load static %}

{% block title %}
Nouvel historique
{% endblock title %}

{% block content %}

<form	action="{% url 'core:object_to_user' default_values.object.pk %}"
		method="post"
		class='history_to_user'
>
	{% csrf_token %}

	<div class='card white z-depth-2'>
		<div class='card-content'>
			<div class='row'>
				<div class='col s12 m6 input-field'>
					<div class='select-wrapper'>
						<select name='{{ form.user.name }}'
						 		id='{{ form.fields.user.id_for_label }}' 
						>
							{% for x,y in form.fields.user.choices %}
		   						<option value='{{ x }}'>{{ y }}</option>
							{% endfor %}
						</select>
						<label for='{{ form.user.id_for_label }}'>
							{{ form.user.label }}
						</label>
					</div>				
				</div>
				<div class='col s12 m6 input-field'>
					<div class='select-wrapper'>
						<select name='{{ form.objectShown.name }}'
								id='{{ form.objectShown.id_for_label }}' 
								disabled
						>
								<option value={{ default_values.object.pk }} selected> {{ default_values.object }}</option>
						</select>
						<label for='{{ form.objectShown.id_for_label }}'>
							{{ form.objectShown.label }}
						</label>
					</div>				
				</div>
			</div>
			<div class='row'>
				<div class='input-field col s12 m6'>
					<input type='date'
						class='datepicker'
						name='{{ form.date.name }}'
						id='{{ form.date.id_for_label}}'
					>
					<label for='{{ form.date.id_for_label }}'>
						{{ form.date.label}}
					</label>
				</div>
				<div class='input-field col s12 m6 select-wrapper'>
					<select name='{{ form.objectState.name }}'
					 		id='{{ form.fields.objectState.id_for_label }}' 
					>
						{% for x,y in form.fields.objectState.choices %}
	   						<option value='{{ x }}'>{{ y }}</option>
						{% endfor %}
					</select>
					<label for='{{ form.objectState.id_for_label }}'>
						{{ form.objectState.label }}
					</label>
				</div>
			</div>
			<div class='row input-field'>
				{{ form.position }}
				<label for='{{ form.position.id_for_label }}'>
					{{ form.position.label }}
				</label>
			</div>
		</div>
	</div>
	<button class='btn btn-submit waves-effect waves-light indigo right disabled'>
	   	Ajouter
	   	<i class="material-icons right">send</i>
	</button>
</form>

{% endblock content %}

{% block script %}

<!-- Selection list form -->
<script src="{% static "js/load/load_select.js" %}">
</script>

<!-- Datepicker form -->
<script src="{% static "js/load/load_datepicker_fr.js" %}">
</script>

<!-- Form button enabler -->
<script src="{% static 'js/form_button.js'%} ">
</script>

<script>
	set_form_checker('.history_to_user');
</script>
{% endblock script %}

Sources/project/core/templates/forms/login.html
{% extends 'main.html' %}
{% load static %}


{% block content %}

Connectez vous:

<form	action='{% url 'core:login' %}'
		method='post'
>

{% csrf_token %}

{{form}}

<button type='submit'>send</button>

</form>
{% endblock content %}

Sources/project/core/templates/forms/object_new.html
{% extends "main.html" %}
{% load static %}

{% block title %}
Ajout d'objet
{% endblock title %}

{% block content %}

<div id="add_object">

<div class='ajax'>
	{% include "./formset_template/object_data.html" %}
</div>

<form action="{% url 'core:object_new' %}" method="post">
	{% csrf_token %}

	<div class='card white z-depth-2'>
		<div class='card-content'>
			<div class='row'>
				<div class='input-field col s12 m6'>
				{% with form_elem=formObject.name form_type='text' prefix_icon='' %}
					{% include 'form_template.html'%}
				{% endwith %}
			</div>

			<div class='input-field col s12 m6 select-wrapper'>
				<select name='{{ formObject.objectType.name }}'
				 		id='{{ formObject.fields.objectType.id_for_label }}' 
						class='object_type_select'
				>
					{% for x,y in formObject.fields.objectType.choices %}
   						<option value='{{ x }}'> {{ y }}</option>
					{% endfor %}
				</select>
				<label for='{{ formObject.objectType.id_for_label }}'>
					{{ formObject.objectType.label }}
				</label>
			</div>
		</div>
	</div>
</div>

	<div class='manage-objectData'>
		{{ formsetObjectData.management_form }}
	</div>
	
	{% for form in formsetObjectData %}
		/!\ This should not be displayed /!\ [/new/object.html]
	{% endfor %}

	<button id='btn-send'
			class='btn waves-effect waves-light indigo disabled right'
	>
	   	Ajouter
	   	<i class="material-icons right">send</i>
	</button>
</form>

</div>

{% endblock content %}

{% block script %}

<!-- Selection list form -->
<script src="{% static "js/load/load_select.js" %}">
</script>

<!-- Tabs to select which form to use -->
<script src="{% static "js/load/load_tabs.js" %}">
</script>

<!-- Add form inputs for objectTypeForm spec -->
<script src="{% static "js/formset.js" %}">
</script>

<script>
	$('#new_objectDataType').click({'form_name': 'objectDataType'}, event_form_add);
</script>


<!-- Dynamic form for add_object part -->
<script>

function    load_object_type()
{
    selected = parseInt($(this).val());
	console.log(selected);
	if (selected >= 1)
    {
	    $.ajax(
        {
	           	url: '{% url 'core:get_type_form' %}',
				data: {'objectType': selected},
				dataType: 'json',
				success: function (data) {
					var selected = select_last_form_name('objectData');

					while (selected != 'form-__prefix__-objectData')
					{
						$('.' + selected).remove();
						selected = select_last_form_name('objectData');
					}

     				var parsed_data = eval(data.objectType);
					console.log('Parsed data:');
     				console.log(parsed_data);

					var i = 0;
     				while (parsed_data[i])
     				{
     					if (i == 0)
     					{
     						form_add_after('objectData', $('.manage-objectData'))
     					}
     					else
     					{
     						form_add('objectData');
     					}
						var new_card = $('.' + select_last_form_name('objectData'));
						new_html = new_card.html().replace(/__title__/g, parsed_data[i].fields.name);
						new_card.find('.form_inner').remove();
						new_card.prepend(new_html);

						new_card.find('.object_data_select').val(parsed_data[i].pk);

						i = i + 1;
					}
                }
			}
		);
		$('#btn-send').removeClass('disabled');
	}
	else
	{
		$('#btn-send').addClass('disabled');
	}
}

$('.object_type_select').change(load_object_type);
</script>

{% endblock script %}

Sources/project/core/templates/forms/role_new.html
<form action="/user/role/new" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

Sources/project/core/templates/forms/user_edit.html
{% extends "main.html" %}
{% load static %}

{% block title %}
Edition d'utilisateur
{% endblock title %}

{% block content %}

<h4> Edition d'utilisateur </h4>
<br>
<form	action='{% url 'core:user_edit' user_id %}'
		method='post'
		class='user_edit'>

  {% csrf_token %}

  <div class="row">
    <div class="input-field col s12 m6">
      <i class="material-icons prefix">account_circle</i>
      {{ form.name }}
      <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
    </div>
    <div class="input-field col s12 m6">
      <i class="material-icons prefix">account_circle</i>
      {{ form.forname }}
      <label for="{{ form.forname.id_for_label }}">{{ form.forname.label }}</label>
    </div>
  </div>
  <div class="input-field row">
    <i class="material-icons prefix">email</i>
    {{ form.email }}
    <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
  </div>
  <div class="input-field row">
    <i class="material-icons prefix">vpn_key</i>
    {{ form.oAuthKey }}
    <label for="{{ form.oAuthKey.id_for_label }}">{{ form.oAuthKey.label }}</label>
  </div>
  <div class="input-field row">
    <i class="material-icons prefix">date_range</i>
    <input type="date"
	   class="datepicker"
	   name="{{ form.entryDate.name }}"
	   id="{{ form.entryDate.id_for_label }}"
	   {% if form.entryDate.value != None %}
	   value="{{ form.entryDate.value | stringformat:'s' }}"
	   {% endif %}
	   >
    <label for="{{ form.entryDate.id_for_label }}">{{ form.entryDate.label }}</label>
  </div>
  <div class="input-field row">
    <i class="material-icons prefix">date_range</i>
    <input type="date"
	   class="datepicker"
	   name="{{ form.outDate.name }}"
	   id="{{ form.outDate.id_for_label }}"
	   {% if form.entryDate.value != None %}
	   value="{{ form.outDate.value | stringformat:'s' }}"
	   {% endif %}
	   >
    <label for="{{ form.outDate.id_for_label }}">{{ form.outDate.label }}</label>
  </div>
  <div class="row">
    <div class="input-field col s12 m6">
      <i class="material-icons prefix">group</i>
      {{ form.userRole }}
      <label for="{{ form.userRole.id_for_label }}">{{ form.userRole.label }}</label>
    </div>
    <div class="input-field col s12 m6">
      <i class="material-icons prefix">assignment_ind</i>
      {{ form.userJob }}
      <label for="{{ form.userJob.id_for_label }}">{{ form.userJob.label }}</label>
    </div>
  </div>

   <button class="btn btn-submit waves-effect waves-light indigo right" type="submit" name="action">Enregistrer
    <i class="material-icons right">send</i>
  </button>
</form>

    <a href='{% url 'core:user_info' user_id %}'>
      <button class="btn waves-effect waves-light red left">Annuler
	<i class="material-icons left">cancel</i>
      </button>
    </a>
{% endblock content %}

{% block script %}

<!-- Selection form -->
<script>
  $(document).ready(function(){
    $('select').formSelect();
  });
</script>

<!-- Datepicker form -->
<script src="{% static "js/load/load_datepicker_fr.js" %}">
</script>

<script src="{% static "js/form_button.js" %}">
</script>

<script>
	set_form_checker('.user_edit');
</script>
{% endblock script %}