Sources/project/core/urls.py
from django.urls        import path

from .                  import views

import uuid

app_name='core'
urlpatterns = [

    #########
    # Admin #
    #########

    path('admin/', views.admin, name='admin'),

    ###############
    # UserManager #
    ###############

    # User

    path('user/', views.user_list,
        name = 'user_list'),
    path('user/job', views.user_list_job,
        name = 'user_list'),
    path('user/new', views.user_new,
        name = 'user_new'),
    path('user/edit/<int:user_id>', views.user_edit,
        name = 'user_edit'),
    path('user/<int:user_id>', views.user_info,
        name = "user_info"),
    path('user/delete/<int:user_id>', views.user_delete,
        name = 'user_delete'),
    path('user/job/new', views.job_new,
        name = 'job_new'),

    #################
    # ObjectManager #
    #################

    path('object/', views.object_list,
         name = "object_list"),
    path('object/stock', views.object_stock_list,
         name = "object_stock_list"),
    path('object/new/', views.object_new,
         name = "object_new"),
    path('object/new/type', views.object_type_new,
         name = "object_type_new"),
    path('object/new/get_type_form', views.get_type_form,
        name = "get_type_form"),
    path('object/<uuid:object_id>', views.object_info,
        name = "object_info"),

    ##################
    # HistoryManager #
    ##################

    path('object/change/<uuid:object_id>', views.object_to_stock,
        name = 'object_to_stock'),
    path('object/stock/change/<uuid:object_id>', views.object_to_user,
        name = 'object_to_user'),
    path('object/state/new', views.object_state_new,
        name = 'object_state_new'),

    ##################
    # CommandManager #
    ##################

    path('command/', views.command_list,
        name = 'command_list'),
    path('command/new', views.command_new,
        name = 'command_new'),
    path('command/<uuid:command_id>', views.command_info,
        name = 'command_info'),

    #################
    # VendorManager #
    #################

    path('vendor/', views.vendor_list,
        name = 'vendor_list'),
    path('vendor/new', views.vendor_new,
        name = 'vendor_new'),
    path('vendor/<int:vendor_id>', views.vendor_info,
        name = 'vendor_info'),

    path('login/', views.login, name='login'),
    path('', views.user_list, name='user_list')
]

Sources/project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    path('favicon.ico', favicon_view),
    path('administration/', admin.site.urls),
    path('', include('core.urls')),
]

Sources/project/core/_views/forms.py
from django.shortcuts   import render
from django.http        import HttpResponse
from django.shortcuts   import redirect

from ..models            import User, UserRole, UserJob
from ..models            import Object, ObjectType, ObjectDataType, ObjectData
from ..models            import ObjectHistory, ObjectState
from ..models            import Command, CommandState
from ..models            import Vendor


from ..forms             import UserForm, RoleForm, JobForm
from ..forms             import ObjectForm, ObjectTypeForm, ObjectDataTypeForm
from ..forms             import ObjectDataFormSet, ObjectDataTypeFormSet
from ..forms             import ObjectToStockForm, ObjectToUserForm, ObjectStateForm
from ..forms             import VendorForm, CommandForm
from ..forms             import LoginForm

from ..forms             import Command__object_form, Command__object_data_form
from ..forms             import command_object_formset, command_object_data_formset


from ..utils import render_to_pdf

from django.core.serializers import serialize
import datetime
from array              import array

from ._forms.history    import object_to_stock, object_to_user, object_state_new

from ._forms.user       import user_new, user_edit, user_delete
from ._forms.user       import job_new, job_edit
from ._forms.user       import role_new, role_edit

from ._forms.command    import command_new

from ._forms.vendor     import vendor_new

from ._forms.object     import object_new, object_type_new

from ._forms.auth      import login

Sources/project/core/forms.py
from django             import forms
from django.forms       import ModelForm, formset_factory

from .models                    import User, UserRole, UserJob
from .models                    import Object, ObjectData
from .models                    import ObjectType, ObjectDataType
from .models                    import ObjectHistory, ObjectState

from .models                    import Vendor, Command, CommandState

####################

##########
# Object #
##########

####################

class           ObjectDataForm(forms.ModelForm):

    hidden = forms.IntegerField()

    class       Meta:
        model   = ObjectData
        fields  = ['value']
        labels = {
            'value': 'Valeur',
        }

ObjectDataFormSet = formset_factory(ObjectDataForm, extra = 0)

class           ObjectTypeForm(forms.ModelForm):
    name = forms.CharField(min_length = 4, max_length = 255)
    
    class       Meta:
        model = ObjectType
        fields = ['name']
        labels = {
            'name': 'Nom',
        }


class           ObjectDataTypeForm(forms.ModelForm):
    class       Meta:
        model = ObjectDataType
        fields = ['name', 's_type', 'mendatory', 'visible']
        exclude = ['objectType']
        labels = {
            'name': 'Nom',
            's_type': 'Type de donnée',
            'mendatory': 'Obligatoire',
            'visible': 'Visible'
        }


ObjectDataTypeFormSet = formset_factory(ObjectDataTypeForm, extra = 0)

class           ObjectForm(forms.ModelForm):
    class Meta:
        model = Object
        fields = ['name', 'user', 'objectType']
        exclude = ['depth', 'objectIn', 'command', 'user']
        labels = {
            'name': 'Nom',
            'user': 'Utilisateur',
            'objectType': 'Type d\'object'
        }

####################

###########
# History #
###########

####################

class           ObjectToStockForm(forms.ModelForm):
    class Meta:
        model = ObjectHistory
        fields = ['date', 'comment', 'position', 'objectState']
        exclude = ['user', 'objectShown']
        labels = {
            'date': 'Date de remise',
            'comment': 'Commentaire',
            'position': 'Lieu de remise',
            'objectState': 'Etat de l\'object'
        }

class           ObjectToUserForm(forms.ModelForm):
    class Meta:
        model = ObjectHistory
        fields = ['date', 'position', 'objectState', 'user']
        exclude = ['objectShown', 'comment']
        labels = {
            'date': 'Date de remise',
            'position': 'Lieu de remise',
            'objectState': 'Etat de l\'object',
            'user': 'Utilisateur'
        }

class           ObjectStateForm(forms.ModelForm):
#    CHOICES = (
#        ('1', '#1b5e20'),
#        ('2', '#388e3c'),
#       ('3', '#4caf50'),
#        ('4', '#8bc34a'),
#        ('5', '#cddc39'),
#        ('6', '#ffeb3b'),
#        ('7', '#fbc02d'),
#        ('8', '#f57f17'),
#        ('9', '#ff5722'),
#        ('10', '#f44336')
#    )
#    color = forms.ChoiceField(choices=CHOICES)

    class Meta:
        model = ObjectState
        fields = ['name', 'color']
        labels = {
            'name': 'Nom',
            'color': 'Couleur'
        }

####################

########
# User #
########

####################

class RoleForm(forms.ModelForm):
    class Meta:
        model = UserRole
        fields = ['name']
        labels = {
            'name': 'Nom'
        }
        
class JobForm(forms.ModelForm):
    class Meta:
         model = UserRole
         fields = ['name']
         labels = {
            'name': 'Nom'
         }

class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['forname', 'name', 'email', 'oAuthKey', 'entryDate', 'outDate', 'userRole', 'userJob']
        labels = {
            'forname': 'Prénom',
            'name': 'Nom',
            'email': 'Email',
            'oAuthKey': 'Clef d\'identification',
            'entryDate': 'Date d\'arrivé',
            'outDate': 'Date de départ',
            'userRole': 'Rôle',
            'userJob': 'Poste'   
        }

class VendorForm(forms.ModelForm):
    class Meta:
         model = Vendor
         fields = ['name', 'adress', 'email', 'comment']
         labels = {
            'name': 'Nom',
            'adress': 'Adresse de l\'entreprise',
            'email': 'Email du contact',
            'comment': 'Informations additionnelles'
         }

class CommandForm(forms.ModelForm):

    class Meta:
        model = Command
        fields = '__all__'
        exclude = ['commandState']

class   Command__object_form(forms.ModelForm):

    count = forms.IntegerField(min_value = 1, required = 1)

    class Meta:
        model = Object
        fields = ['name', 'objectType', 'count']

command_object_formset = formset_factory(Command__object_form, extra = 0)

class   Command__object_data_form(forms.ModelForm):
    class Meta:
        model = ObjectData
        fields = ['value', 'objectDataType']

command_object_data_formset = formset_factory(Command__object_data_form, extra = 0)

# Login
class   LoginForm(forms.Form):
    login = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

Sources/project/core/views.py
from django.shortcuts   import render
from django.http        import HttpResponse
from django.shortcuts   import redirect

#from django.core.serializers import serialize
#from django.http        import JsonResponse
#from datetime           import date
#from array              import array

# List views
from ._views.list       import user_list
from ._views.list       import user_list_job
from ._views.list       import object_list
from ._views.list       import object_stock_list
from ._views.list       import command_list
from ._views.list       import vendor_list

# Form views
from ._views.forms      import user_new
from ._views.forms      import job_new
from ._views.forms      import role_new
from ._views.forms      import object_new
from ._views.forms      import object_type_new
from ._views.forms      import object_to_stock
from ._views.forms      import object_to_user
from ._views.forms      import object_state_new
from ._views.forms      import command_new
from ._views.forms      import vendor_new

from ._views.forms      import user_edit
from ._views.forms      import job_edit
from ._views.forms      import role_edit

from ._views.forms      import user_delete

from ._views.forms      import login

# Info views
from ._views.infos      import user_info
from ._views.infos      import object_info
from ._views.infos      import vendor_info
from ._views.infos      import command_info
from ._views.infos      import admin

# Ajax section
from ._views.ajax       import get_type_form

from .models import User, UserRole, UserJob


# TODO: Clean this check (I'm learning django)

# Check for the basic data
if (not (UserRole.objects.filter(name = '__STOCK__').exists())):
    UserRole.objects.create(name = '__STOCK__')

if (not (UserJob.objects.filter(name = '__STOCK__').exists())):
    UserJob.objects.create(name = '__STOCK__')

if (not (User.objects.filter(name = '__STOCK__', forname = '__STOCK__').exists())):
    User.objects.create(
        name = '__STOCK__',
        forname = '__STOCK__',
        oAuthKey = 'None',
        userRole = UserRole.objects.get(name = '__STOCK__'),
        userJob = UserJob.objects.get(name = '__STOCK__'),
    )

if (not (User.objects.filter(name = '__PENDING__', forname = '__PENDING__').exists())):
    User.objects.create(
        name = '__PENDING__',
        forname = '__PENDING__',
        oAuthKey = 'None',
        userRole = UserRole.objects.get(name = '__STOCK__'),
        userJob = UserJob.objects.get(name = '__STOCK__'),
    )

from .models import Object
def test(request):
    get = Object.objects.get(pk = 'cbe29927-c694-4bec-b776-810bc00af604').last_object_state()
    return HttpResponse('Le dernier état de l\'object est: ' + get.objectState.name)

def index(request):
    return HttpResponse("Index: objectManager")

Sources/project/core/templates/infos/admin.html
{% extends "main.html" %}
{% load static %}

{% block content %}

<div class='row'>

	<!-- Material graph -->
	<div class='col s12 m12 l12'>
		<div class='card' style='margin: 5px'>
			<div class='card-title'>
				Matériel
			</div>
			<div class='card-content'>

				<div class='row'>
					<!-- Material graph -->
					<div class='col s12 l6'>
						<div class='row row-vertical-center no-margin'>
							<div class='col s12 m6 l12'>
								<div class='row'>
									<canvas id="myChart"></canvas>
								</div>
							</div>
							<div class='col s12 m6 l12' style='display: flex;justify-content: center;'>
								<ul id='object_labels'>
									{% for object_type in object_types %}
										<li class='row'>
											<i class='tiny material-icons label{{ forloop.counter0 }}'>
												fiber_manual_record
											</i>
											<span class='label'>
												{{ object_type.name }}
											</span>
											<span class='value right'>
												{{ object_type.object_number }}
											</span>
										</li>
						        	{% endfor %}				
								</ul>
							</div>
						</div>
					</div>

				<div class='col s12 l6'>
					<div class='row row-vertical-center no-margin'>
						<div id='stock'>
							<ul class='collapsible'>
								<li>			
									<div class='collapsible-header indigo white-text'>
										Matériel en stock:
										<span class="new badge white indigo-text right" data-badge-caption="">{{ objects_stock|length }}</span>
									</div>
								</li>
							</ul>
							<ul class='collapsible'>
							{% regroup objects_stock by objectType.name as objects_type_stock %}
							{% for objects_stock_type in objects_type_stock %}
								<li>			
									<div class='collapsible-header'>
										{{ objects_stock_type.grouper }}
										<span class="new badge indigo white-text right" data-badge-caption="">{{ objects_stock_type.list|length }}</span>
									</div>
									<div class='collapsible-body'>
										<canvas id='object_stock_state{{forloop.couter0}}' height=70></canvas>
										{% regroup objects_stock_type.list by state.name as objects_stock_state %}
										{% for lol in objects_stock_state %}
											{% for object_assigned in lol.list %}
											{% endfor %}
										{% endfor %}
									</div>
								</li>
							{% endfor %}
							</ul>
							<br>
						</div>

						<div id='assigned'>
							<ul class='collapsible'>
								<li>			
									<div class='collapsible-header indigo white-text'>
										Matériel attribue:
										<span class="new badge white indigo-text right" data-badge-caption="">{{ objects_assigned|length }}</span>
									</div>
								</li>
							</ul>
							<ul class='collapsible'>
							{% regroup objects_assigned by objectType.name as objects_type_assigned %}	
								{% for objects_assigned_type in objects_type_assigned %}
									<li>
										<div class="collapsible-header">{{ objects_assigned_type.grouper }}
											<span class="new badge indigo white-text right" data-badge-caption="">{{ objects_assigned_type.list|length }}</span>
										</div>
										<div class="collapsible-body">
											<br>
											<canvas id='object_assigned_state{{forloop.counter0}}' height=70></canvas>
											{% regroup objects_assigned_type.list by state.name as objects_assigned_state %}
											{% for lol in objects_assigned_state %}
												{% for object_assigned in lol.list %}
												{% endfor %}
											{% endfor %}
										</div>
									</li>
								{% endfor %}
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

</div>
{% endblock content %}

{% block script %}

<!-- Load tabs-->
<script src='{% static 'js/load/load_tabs.js' %}'>
</script>

<!-- Load chartjs-->
<script src='{% static 'js/chart.js' %}'>
</script>

<!-- Get material_colors-->
<script src='{% static 'js/material_colors.js' %}'>
</script>

<!-- ChartJS Part-->
<script>

/* Colors part */
function shuffleArray(array) {
    for (var i = array.length - 1; i > 0; i--) {
        var j = Math.floor(Math.random() * (i + 1));
        var temp = array[i];
        array[i] = array[j];
        array[j] = temp;
    }
    return array;
}
colors = shuffleArray(material_colors_array);

/* Label for object doughnut */
for(i = 0; i < {{object_types|length }}; i++)
{
	$('.label' + i).css('color', colors[i]);
}

/* doughnut */
Chart.defaults.global.legend.display = false;

var ctx = document.getElementById('myChart').getContext('2d');

var myChart = new Chart(ctx, {
    type: 'doughnut',
    options: {
		cutoutPercentage: 80,
    },
    data: {
        labels:
        [
			{% for object_type in object_types %}
				'{{ object_type.name }}',
        	{% endfor %}
        ],
        datasets: [{
            data:
            [
			{% for object_type in object_types %}
				{{ object_type.object_number }},
        	{% endfor %}
           	 ],
            backgroundColor: colors,
            borderWidth: 0
        }]
    },
});

var barOptions_stacked = {
    tooltips: {
        enabled: true
    },
    hover :{
        animationDuration:0
    },
    scales: {
        xAxes: [{
            ticks: {
                beginAtZero:true,
                fontFamily: "'Open Sans Bold', sans-serif",
                fontSize:11
            },
            scaleLabel:{
                display:false
            },
            gridLines: {
            	display: false,
            }, 
            stacked: true
        }],
        yAxes: [{
            gridLines: {
                display:false,
                color: "#fff",
                zeroLineColor: "#fff",
                zeroLineWidth: 0
            },
            scaleLabel:{
                display:false
            },
            ticks: {
                fontFamily: "'Open Sans Bold', sans-serif",
                fontSize:11
            },
            stacked: true
        }]
    },
    legend:
    {
        display:false
    },
};

/* Lines */
//Chart.defaults.global.legend.display = true;

{% regroup objects_assigned by objectType.name as objects_type_assigned %}
{% for objects_assigned_type in objects_type_assigned %}
	
	//{{ objects_assigned_type.grouper }} | {{ objects_assigned_type.list|length }}<br>
	
	var bar_zone = document.getElementById('object_assigned_state' + {{ forloop.counter0 }}).getContext('2d');
	
	
	{% regroup objects_assigned_type.list by state.name as objects_assigned_state %}
	
	/* Loading data */
	var bar_datasets = [];
	var bar_data = [];
	var bar_labels = [];
	var bar_colors = [];

	var i = 0;
	{% for states_values in objects_assigned_state %}
		bar_data.push( {{ states_values.list|length }} );
		bar_labels.push( '{{ states_values.grouper }}' );
		{% with states_values.list|first as first_elem %}
			bar_colors.push('{{ first_elem.state.color }}');
		{% endwith %}
		console.log(bar_colors);
		bar_datasets.push(
			{
				label: bar_labels[i],
				data: [bar_data[i]],
				backgroundColor: bar_colors[i],
		 	}
		 );
		i = i + 1;
	{% endfor %}
	console.log(bar_datasets);

	var myBarChart = new Chart(
		bar_zone,
		{
		    type: 'horizontalBar',
		    data:
		    {
		    	//labels: bar_data,
		    	datasets: bar_datasets,
			},
			options: barOptions_stacked,
			
		}
	);
{% endfor %}

</script>

{% endblock script %}

Sources/project/core/templates/infos/object.html
{% extends "main.html" %}
{% load static %}

{% block content %}

	{% if object %}

		<div class="card indigo darken-1">
			<div class="card-content white-text">

				<span class="card-title"><h4>{{ object.name }}</h4></span>

				<br>
				<div class="card-action"></div>

				<div class="row">
					<h5>Informations:</h5>
					<br>
					<div class="col s12 m6">
						<strong><U>Type:</U></strong> {{ object.objectType.name }}<br>
						<strong><U>Appartient à:</U></strong> {{ object.user.forname }} {{ object.user.name }}<br>
					</div>
					<div class="col s12 m6 right">
						<strong><U>Commande:</U></strong> {{ object.command.ref | default:"Inconnue"}}<br>
						<strong><U>Date d'arrivée:</U></strong> Inconnue <br>
					</div>
				</div>

				{% if objectData %}
					<div class="card-action"></div>
	
					<div class="row">
						<h5>Spécifications:</h5>
						<br>
						<div class='container'>
						<table class='white indigo-text stripped centered'>
							<tr>
								<th>Nom</th>
									{% for data in objectData %}
										<td>{{ data.objectDataType.name }}</td>
									{% endfor %}
							</tr>
							<tr>
								<th>Valeur</th>
								{% for data in objectData %}
									<td> {{ data.value }}</td>
								{% endfor %}
							</tr>
						</table>
					</div>

				</div>
				{% endif %}
			</div>


			<div class="card-action">

					<a class="indigo-text" href="{% url 'core:object_to_stock' object.pk %}">
						<button class="btn waves-effect waves-light indigo-text white left ">
							Formulaire
						</button>
					</a>

			</div>
			<br>
		</div>

	{% else %}
	
		<h1 class='align-center'>L'objet indiqué n'existe pas</h1>
		
	{% endif %}

{% endblock content %}

Sources/project/core/templates/infos/user.html
{% extends "main.html" %}
{% load static %}


{% if user %}

{% block content %}

<div class="card indigo darken-1">
  <div class="card-content white-text">
    <span class="card-title"><h4>{{user.forname}} {{user.name}}</h4></span>
    <br>
    <div class="card-action"></div>
    <div class="row">
      <h5>Informations personnelles:</h5>
      <br>
      <div class="col s12 m6">
	<strong><U>Role:</U></strong> {{user.userRole.name | default:"Non fournis"}}<br>
	<strong><U>Date d'entrée:</U></strong> {{user.entryDate | default:"Non fournie"}}<br>
	<strong><U>Nom du poste:</U></strong> {{user.userJob.name }}<br>
      </div>
      <div class="col s12 m6 right">
	<strong><U>Email:</U></strong> {{user.email | default:"Non fournie"}}<br>
	<strong><U>Date de sortie:</U></strong> {{user.outDate | default:"Non connue"}}<br>
      </div>
    </div>
  </div>
	{% include './user__object.html' %}

  <div class="card-action">
	<a class="btn waves-effect waves-light red right modal-trigger" href="#modal1">
		Supprimer
	</a>

    <a class="indigo-text" href="{% url 'core:user_edit' user.pk %}">
      <button class="btn waves-effect waves-light indigo-text white left">
	Editer
      </button>
    </a>
  </div>
  <br>
</div>

 <!-- Modal Structure -->
  <div id="modal1" class="modal">
    <div class="modal-content">
      <h4>Êtes vous sûr ?</h4>
      <p>La supression d'un utilisateur inclut la supression de l'utilisateur, ainsi que tous les objets non remis.</p>
    </div>
    <div class="modal-footer">
      <a href="#!" class="modal-close waves-effect waves-green btn-flat">Annuler</a>
      <a href="{% url 'core:user_delete' user.pk %}" class="modal-close waves-effect waves-green btn-flat">Confirmer</a>
    </div>
  </div>


{% endblock content %}

{% block script %}

<script src='{% static 'js/load_modal.js' %}'>
</script>

{% endblock script %}

{% endif %}

Sources/project/core/templates/infos/user__object.html
<div class='card-action'>
</div>

{% if objects %}

<div class='card-content white-text'>
	<div class='white-text'>

		<h5>Objets</h5>
		<br>

		{% for object in objects %}

		    {% if object.depth == 0 %}

				<div class='card-panel white'>
				
						<div class='row indigo-text valign-wrapper'>
								<h5> {{ object.objectType.name }} - {{ object.name }}</h5>
						</div>
						<div class='card-action'></div>

						<span class='indigo-text'>
						<div class='row'>
                            <div class=''>
    	                        <table style=''>
     		                       	<thead>
										<tr>
		  		  						    {% for data in datas %}
												{% if data.item.pk == object.pk %}
														<th>{{ data.objectDataType.name }}</th>		
			                	                    {% endif %}
		  		  						    {% endfor %}
										</tr>
 							    	</thead>
 							    	<tbody>
										<tr>
  		  						    {% for data in datas %}
        	                            {% if data.item.pk == object.pk %}
												<td>{{ data.value }}</td>		
											{% endif %}
  		  						    {% endfor %}
  		  						    </tr>
 		   						    </tbody>
	    						</table>
	    						<br>
						    </div>

						</div>
						</span>

						<div class='card-action'>
							<a class='' href='/object/{{object.ref }}'>Description</a>
							<a class='right' href={% url 'core:object_to_stock' object.ref %}>Formulaire de restitution</a>
						</div>
				</div>				

            {% endif %}
			
	{% endfor %}
	</div>
</div>
{% else %}
<div class='center-align white-text'>
	{{user.name}} {{user.forname}} n'a pas de matériel attribué.
</div>
<br>
{% endif %}